{% set name = "openpmd-beamphysics" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 53bc76ea2ffef49715bc2c36a1ea619ac77536dd17fbc4934a13f7ea8727bf09

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - scipy >=1.0.0
    - h5py
    - python-dateutil

test:
  requires:
    - python {{ python_min }}
  imports:
    - pmd_beamphysics

about:
  home: https://github.com/ChristopherMayes/openPMD-beamphysics
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Tools for analyzing and viewing particle data in the openPMD standard, extension beamphysics.
  description: |
    Tools for analyzing and viewing particle data in the openPMD standard,
    extension beamphysics.

extra:
  recipe-maintainers:
    - ken-lauer
    - ChristopherMayes
