{% set name = "openpmd-beamphysics" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: a01b296913311934f1d9c8d44c91260e70f9deb5fb80648f72a67066241f871f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - scipy >=1.0.0
    - h5py
    - python-dateutil

test:
  requires:
    - python {{ python_min }}
  imports:
    - beamphysics
    - beamphysics.fields
    - beamphysics.interfaces
    - beamphysics.standards
    - beamphysics.wakefields
    - beamphysics.wavefront
    # Deprecated package name for back-compat:
    - pmd_beamphysics
    - pmd_beamphysics.fields
    - pmd_beamphysics.interfaces
    - pmd_beamphysics.standards
    - pmd_beamphysics.wakefields
    - pmd_beamphysics.wavefront

about:
  home: https://github.com/ChristopherMayes/openPMD-beamphysics
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Tools for analyzing and viewing particle data in the openPMD standard, extension beamphysics.
  description: |
    Tools for analyzing and viewing particle data in the openPMD standard,
    extension beamphysics.

extra:
  recipe-maintainers:
    - ken-lauer
    - ChristopherMayes
